//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.08 at 08:17:36 PM EET 
//


package com.gillsoft.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for item_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="item_type">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="kind" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cost" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="vat" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="fee" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="ticket" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="reserved_seat" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="commission" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="carrier" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="reserved_seat_percent" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="ticket_percent" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="return" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="vat_return" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="pay_commision" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="com_service" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="insurance" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "item_type", propOrder = {
    "value"
})
public class ItemType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "code")
    protected String code;
    @XmlAttribute(name = "kind")
    protected String kind;
    @XmlAttribute(name = "cost")
    protected Float cost;
    @XmlAttribute(name = "vat")
    protected Float vat;
    @XmlAttribute(name = "fee")
    protected Float fee;
    @XmlAttribute(name = "ticket")
    protected Float ticket;
    @XmlAttribute(name = "reserved_seat")
    protected Float reservedSeat;
    @XmlAttribute(name = "commission")
    protected Float commission;
    @XmlAttribute(name = "carrier")
    protected Float carrier;
    @XmlAttribute(name = "reserved_seat_percent")
    protected Float reservedSeatPercent;
    @XmlAttribute(name = "ticket_percent")
    protected Float ticketPercent;
    @XmlAttribute(name = "return")
    protected Float _return;
    @XmlAttribute(name = "vat_return")
    protected Float vatReturn;
    @XmlAttribute(name = "pay_commision")
    protected Float payCommision;
    @XmlAttribute(name = "com_service")
    protected Float comService;
    @XmlAttribute(name = "insurance")
    protected Float insurance;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKind(String value) {
        this.kind = value;
    }

    /**
     * Gets the value of the cost property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCost(Float value) {
        this.cost = value;
    }

    /**
     * Gets the value of the vat property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVat() {
        return vat;
    }

    /**
     * Sets the value of the vat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVat(Float value) {
        this.vat = value;
    }

    /**
     * Gets the value of the fee property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFee() {
        return fee;
    }

    /**
     * Sets the value of the fee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFee(Float value) {
        this.fee = value;
    }

    /**
     * Gets the value of the ticket property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTicket() {
        return ticket;
    }

    /**
     * Sets the value of the ticket property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTicket(Float value) {
        this.ticket = value;
    }

    /**
     * Gets the value of the reservedSeat property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getReservedSeat() {
        return reservedSeat;
    }

    /**
     * Sets the value of the reservedSeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setReservedSeat(Float value) {
        this.reservedSeat = value;
    }

    /**
     * Gets the value of the commission property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCommission() {
        return commission;
    }

    /**
     * Sets the value of the commission property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCommission(Float value) {
        this.commission = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCarrier(Float value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the reservedSeatPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getReservedSeatPercent() {
        return reservedSeatPercent;
    }

    /**
     * Sets the value of the reservedSeatPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setReservedSeatPercent(Float value) {
        this.reservedSeatPercent = value;
    }

    /**
     * Gets the value of the ticketPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTicketPercent() {
        return ticketPercent;
    }

    /**
     * Sets the value of the ticketPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTicketPercent(Float value) {
        this.ticketPercent = value;
    }

    /**
     * Gets the value of the return property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getReturn() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setReturn(Float value) {
        this._return = value;
    }

    /**
     * Gets the value of the vatReturn property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVatReturn() {
        return vatReturn;
    }

    /**
     * Sets the value of the vatReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVatReturn(Float value) {
        this.vatReturn = value;
    }

    /**
     * Gets the value of the payCommision property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPayCommision() {
        return payCommision;
    }

    /**
     * Sets the value of the payCommision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPayCommision(Float value) {
        this.payCommision = value;
    }

    /**
     * Gets the value of the comService property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getComService() {
        return comService;
    }

    /**
     * Sets the value of the comService property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setComService(Float value) {
        this.comService = value;
    }

    /**
     * Gets the value of the insurance property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getInsurance() {
        return insurance;
    }

    /**
     * Sets the value of the insurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setInsurance(Float value) {
        this.insurance = value;
    }

}
