//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.08 at 08:17:36 PM EET 
//


package com.gillsoft.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for locality_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="locality_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="arrival_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="departure_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="days" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="railway" type="{}railway_type"/>
 *       &lt;/sequence>
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="railway" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name_uk" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name_ru" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name_lt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "locality_type", propOrder = {
    "code",
    "name",
    "arrivalTime",
    "departureTime",
    "distance",
    "days",
    "railway"
})
public class LocalityType {

    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "arrival_time", required = true)
    protected String arrivalTime;
    @XmlElement(name = "departure_time", required = true)
    protected String departureTime;
    @XmlElement(required = true)
    protected String distance;
    @XmlElement(required = true)
    protected String days;
    @XmlElement(required = true)
    protected RailwayType railway;
    @XmlAttribute(name = "code")
    protected String codeAttr;
    @XmlAttribute(name = "city")
    protected String city;
    @XmlAttribute(name = "railway")
    protected String railwayAttr;
    @XmlAttribute(name = "name_uk")
    protected String nameUk;
    @XmlAttribute(name = "name_ru")
    protected String nameRu;
    @XmlAttribute(name = "name_lt")
    protected String nameLt;

	/**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the arrivalTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalTime() {
        return arrivalTime;
    }

    /**
     * Sets the value of the arrivalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalTime(String value) {
        this.arrivalTime = value;
    }

    /**
     * Gets the value of the departureTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureTime() {
        return departureTime;
    }

    /**
     * Sets the value of the departureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureTime(String value) {
        this.departureTime = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistance(String value) {
        this.distance = value;
    }

    /**
     * Gets the value of the days property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDays() {
        return days;
    }

    /**
     * Sets the value of the days property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDays(String value) {
        this.days = value;
    }

    /**
     * Gets the value of the railway property.
     * 
     * @return
     *     possible object is
     *     {@link RailwayType }
     *     
     */
    public RailwayType getRailway() {
        return railway;
    }

    /**
     * Sets the value of the railway property.
     * 
     * @param value
     *     allowed object is
     *     {@link RailwayType }
     *     
     */
    public void setRailway(RailwayType value) {
        this.railway = value;
    }

    /**
     * Gets the value of the codeAttr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeAttr() {
        return codeAttr;
    }

    /**
     * Sets the value of the codeAttr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeAttr(String value) {
        this.codeAttr = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the railwayAttr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRailwayAttr() {
        return railwayAttr;
    }

    /**
     * Sets the value of the railwayAttr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRailwayAttr(String value) {
        this.railwayAttr = value;
    }

    /**
     * Gets the value of the nameUk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameUk() {
        return nameUk;
    }

    /**
     * Sets the value of the nameUk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameUk(String value) {
        this.nameUk = value;
    }

    /**
     * Gets the value of the nameRu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameRu() {
        return nameRu;
    }

    /**
     * Sets the value of the nameRu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameRu(String value) {
        this.nameRu = value;
    }

    /**
     * Gets the value of the nameLt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLt() {
        return nameLt;
    }

    /**
     * Sets the value of the nameLt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLt(String value) {
        this.nameLt = value;
    }

}
