//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.11 at 08:54:19 AM EET 
//


package com.gillsoft.client;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gillsoft.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResponseTransactionCountriesCountry_QNAME = new QName("", "country");
    private final static QName _RequestTransactionDate_QNAME = new QName("", "date");
    private final static QName _RequestTransactionFirstname_QNAME = new QName("", "firstname");
    private final static QName _RequestTransactionDocuments_QNAME = new QName("", "documents");
    private final static QName _RequestTransactionQrcode_QNAME = new QName("", "qrcode");
    private final static QName _RequestTransactionWagonClass_QNAME = new QName("", "wagon_class");
    private final static QName _RequestTransactionUid_QNAME = new QName("", "uid");
    private final static QName _RequestTransactionWagonNumber_QNAME = new QName("", "wagon_number");
    private final static QName _RequestTransactionPassport_QNAME = new QName("", "passport");
    private final static QName _RequestTransactionReserveId_QNAME = new QName("", "reserve_id");
    private final static QName _RequestTransactionUio_QNAME = new QName("", "uio");
    private final static QName _RequestTransactionBarcode_QNAME = new QName("", "barcode");
    private final static QName _RequestTransactionTrain_QNAME = new QName("", "train");
    private final static QName _RequestTransactionSrcId_QNAME = new QName("", "src_id");
    private final static QName _RequestTransactionDate1_QNAME = new QName("", "date1");
    private final static QName _RequestTransactionTransactionType_QNAME = new QName("", "transaction_type");
    private final static QName _RequestTransactionLastname_QNAME = new QName("", "lastname");
    private final static QName _RequestTransactionCodeStationTo_QNAME = new QName("", "code_station_to");
    private final static QName _RequestTransactionPlaces_QNAME = new QName("", "places");
    private final static QName _RequestTransactionFiscal_QNAME = new QName("", "fiscal");
    private final static QName _RequestTransactionBinary_QNAME = new QName("", "binary");
    private final static QName _RequestTransactionName_QNAME = new QName("", "name");
    private final static QName _RequestTransactionWagonType_QNAME = new QName("", "wagon_type");
    private final static QName _RequestTransactionFiscalId_QNAME = new QName("", "fiscal_id");
    private final static QName _RequestTransactionCountrystation_QNAME = new QName("", "countrystation");
    private final static QName _RequestTransactionCodeStationFrom_QNAME = new QName("", "code_station_from");
    private final static QName _RequestTransactionDocumentsDocument_QNAME = new QName("", "document");


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gillsoft.client
     * 
     */
    public ObjectFactory() {
    }
    
    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link WagonType }
     * 
     */
    public WagonType createWagonType() {
        return new WagonType();
    }

    /**
     * Create an instance of {@link CountryType }
     * 
     */
    public CountryType createCountryType() {
        return new CountryType();
    }

    /**
     * Create an instance of {@link DetailType }
     * 
     */
    public DetailType createDetailType() {
        return new DetailType();
    }

    /**
     * Create an instance of {@link TicketType }
     * 
     */
    public TicketType createTicketType() {
        return new TicketType();
    }
    
    /**
     * Create an instance of {@link Request.Transaction }
     * 
     */
    public Request.Transaction createRequestTransaction() {
        return new Request.Transaction();
    }

    /**
     * Create an instance of {@link Response.Transaction }
     * 
     */
    public Response.Transaction createResponseTransaction() {
        return new Response.Transaction();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link CostType }
     * 
     */
    public CostType createCostType() {
        return new CostType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link RailwayType }
     * 
     */
    public RailwayType createRailwayType() {
        return new RailwayType();
    }

    /**
     * Create an instance of {@link TrainType }
     * 
     */
    public TrainType createTrainType() {
        return new TrainType();
    }

    /**
     * Create an instance of {@link SeatsType }
     * 
     */
    public SeatsType createSeatsType() {
        return new SeatsType();
    }

    /**
     * Create an instance of {@link PlacesType }
     * 
     */
    public PlacesType createPlacesType() {
        return new PlacesType();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link LocalityType }
     * 
     */
    public LocalityType createLocalityType() {
        return new LocalityType();
    }

    /**
     * Create an instance of {@link PassportType }
     * 
     */
    public PassportType createPassportType() {
        return new PassportType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link DocumentType.Costs }
     * 
     */
    public DocumentType.Costs createDocumentTypeCosts() {
        return new DocumentType.Costs();
    }

    /**
     * Create an instance of {@link DocumentType.Withholding }
     * 
     */
    public DocumentType.Withholding createDocumentTypeWithholding() {
        return new DocumentType.Withholding();
    }

    /**
     * Create an instance of {@link WagonType.Service }
     * 
     */
    public WagonType.Service createWagonTypeService() {
        return new WagonType.Service();
    }

    /**
     * Create an instance of {@link CountryType.Stations }
     * 
     */
    public CountryType.Stations createCountryTypeStations() {
        return new CountryType.Stations();
    }

    /**
     * Create an instance of {@link CountryType.Railways }
     * 
     */
    public CountryType.Railways createCountryTypeRailways() {
        return new CountryType.Railways();
    }

    /**
     * Create an instance of {@link CountryType.Cities }
     * 
     */
    public CountryType.Cities createCountryTypeCities() {
        return new CountryType.Cities();
    }

    /**
     * Create an instance of {@link DetailType.Reserve }
     * 
     */
    public DetailType.Reserve createDetailTypeReserve() {
        return new DetailType.Reserve();
    }

    /**
     * Create an instance of {@link TicketType.FiscalInfo }
     * 
     */
    public TicketType.FiscalInfo createTicketTypeFiscalInfo() {
        return new TicketType.FiscalInfo();
    }
    
    /**
     * Create an instance of {@link Request.Transaction.Documents }
     * 
     */
    public Request.Transaction.Documents createRequestTransactionDocuments() {
        return new Request.Transaction.Documents();
    }

    /**
     * Create an instance of {@link Request.Transaction.Binary }
     * 
     */
    public Request.Transaction.Binary createRequestTransactionBinary() {
        return new Request.Transaction.Binary();
    }

    /**
     * Create an instance of {@link Response.Transaction.Trains }
     * 
     */
    public Response.Transaction.Trains createResponseTransactionTrains() {
        return new Response.Transaction.Trains();
    }

    /**
     * Create an instance of {@link Response.Transaction.Countries }
     * 
     */
    public Response.Transaction.Countries createResponseTransactionCountries() {
        return new Response.Transaction.Countries();
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionDate(String value) {
        return new JAXBElement<String>(_RequestTransactionDate_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "firstname", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionFirstname(String value) {
        return new JAXBElement<String>(_RequestTransactionFirstname_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Request.Transaction.Documents }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "documents", scope = Request.Transaction.class)
    public JAXBElement<Request.Transaction.Documents> createRequestTransactionDocuments(Request.Transaction.Documents value) {
        return new JAXBElement<Request.Transaction.Documents>(_RequestTransactionDocuments_QNAME, Request.Transaction.Documents.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "qrcode", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionQrcode(String value) {
        return new JAXBElement<String>(_RequestTransactionQrcode_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wagon_class", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionWagonClass(String value) {
        return new JAXBElement<String>(_RequestTransactionWagonClass_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "uid", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionUid(String value) {
        return new JAXBElement<String>(_RequestTransactionUid_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wagon_number", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionWagonNumber(String value) {
        return new JAXBElement<String>(_RequestTransactionWagonNumber_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PassportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "passport", scope = Request.Transaction.class)
    public JAXBElement<PassportType> createRequestTransactionPassport(PassportType value) {
        return new JAXBElement<PassportType>(_RequestTransactionPassport_QNAME, PassportType.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reserve_id", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionReserveId(String value) {
        return new JAXBElement<String>(_RequestTransactionReserveId_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "uio", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionUio(String value) {
        return new JAXBElement<String>(_RequestTransactionUio_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "barcode", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionBarcode(String value) {
        return new JAXBElement<String>(_RequestTransactionBarcode_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "train", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionTrain(String value) {
        return new JAXBElement<String>(_RequestTransactionTrain_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "src_id", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionSrcId(String value) {
        return new JAXBElement<String>(_RequestTransactionSrcId_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date1", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionDate1(String value) {
        return new JAXBElement<String>(_RequestTransactionDate1_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "transaction_type", scope = Request.Transaction.class)
    public JAXBElement<Byte> createRequestTransactionTransactionType(Byte value) {
        return new JAXBElement<Byte>(_RequestTransactionTransactionType_QNAME, Byte.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastname", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionLastname(String value) {
        return new JAXBElement<String>(_RequestTransactionLastname_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "code_station_to", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionCodeStationTo(String value) {
        return new JAXBElement<String>(_RequestTransactionCodeStationTo_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "places", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionPlaces(String value) {
        return new JAXBElement<String>(_RequestTransactionPlaces_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fiscal", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionFiscal(String value) {
        return new JAXBElement<String>(_RequestTransactionFiscal_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Request.Transaction.Binary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "binary", scope = Request.Transaction.class)
    public JAXBElement<Request.Transaction.Binary> createRequestTransactionBinary(Request.Transaction.Binary value) {
        return new JAXBElement<Request.Transaction.Binary>(_RequestTransactionBinary_QNAME, Request.Transaction.Binary.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionName(String value) {
        return new JAXBElement<String>(_RequestTransactionName_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wagon_type", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionWagonType(String value) {
        return new JAXBElement<String>(_RequestTransactionWagonType_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fiscal_id", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionFiscalId(String value) {
        return new JAXBElement<String>(_RequestTransactionFiscalId_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "countrystation", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionCountrystation(String value) {
        return new JAXBElement<String>(_RequestTransactionCountrystation_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "code_station_from", scope = Request.Transaction.class)
    public JAXBElement<String> createRequestTransactionCodeStationFrom(String value) {
        return new JAXBElement<String>(_RequestTransactionCodeStationFrom_QNAME, String.class, Request.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "document", scope = Request.Transaction.Documents.class)
    public JAXBElement<DocumentType> createRequestTransactionDocumentsDocument(DocumentType value) {
        return new JAXBElement<DocumentType>(_RequestTransactionDocumentsDocument_QNAME, DocumentType.class, Request.Transaction.Documents.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country", scope = Response.Transaction.Countries.class)
    public JAXBElement<CountryType> createResponseTransactionCountriesCountry(CountryType value) {
        return new JAXBElement<CountryType>(_ResponseTransactionCountriesCountry_QNAME, CountryType.class, Response.Transaction.Countries.class, value);
    }

}
