//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.08 at 08:17:36 PM EET 
//


package com.gillsoft.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for order_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="order_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="electronic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paydate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ordernumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="barcode_image" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="returndate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ticket" type="{}ticket_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="documents" type="{}ticket_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "order_type", propOrder = {
    "electronic",
    "paydate",
    "ordernumber",
    "barcodeImage",
    "uio",
    "returndate",
    "ticket",
    "documents"
})
public class OrderType {

    @XmlElement(required = true)
    protected String electronic;
    @XmlElement(required = true)
    protected String paydate;
    @XmlElement(required = true)
    protected String ordernumber;
    @XmlElement(name = "barcode_image", required = true)
    protected String barcodeImage;
    @XmlElement(required = true)
    protected String uio;
    @XmlElement(required = true)
    protected String returndate;
    protected List<TicketType> ticket;
    protected List<TicketType> documents;

    /**
     * Gets the value of the electronic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElectronic() {
        return electronic;
    }

    /**
     * Sets the value of the electronic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElectronic(String value) {
        this.electronic = value;
    }

    /**
     * Gets the value of the paydate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaydate() {
        return paydate;
    }

    /**
     * Sets the value of the paydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaydate(String value) {
        this.paydate = value;
    }

    /**
     * Gets the value of the ordernumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * Sets the value of the ordernumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdernumber(String value) {
        this.ordernumber = value;
    }

    /**
     * Gets the value of the barcodeImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarcodeImage() {
        return barcodeImage;
    }

    /**
     * Sets the value of the barcodeImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarcodeImage(String value) {
        this.barcodeImage = value;
    }

    /**
     * Gets the value of the uio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUio() {
        return uio;
    }

    /**
     * Sets the value of the uio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUio(String value) {
        this.uio = value;
    }

    /**
     * Gets the value of the returndate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturndate() {
        return returndate;
    }

    /**
     * Sets the value of the returndate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturndate(String value) {
        this.returndate = value;
    }

    /**
     * Gets the value of the ticket property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ticket property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTicket().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TicketType }
     * 
     * 
     */
    public List<TicketType> getTicket() {
        if (ticket == null) {
            ticket = new ArrayList<TicketType>();
        }
        return this.ticket;
    }

    /**
     * Gets the value of the documents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocuments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TicketType }
     * 
     * 
     */
    public List<TicketType> getDocuments() {
        if (documents == null) {
            documents = new ArrayList<TicketType>();
        }
        return this.documents;
    }

}
