//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.08 at 08:17:36 PM EET 
//


package com.gillsoft.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for places_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="places_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lower" type="{}seats_type" minOccurs="0"/>
 *         &lt;element name="top" type="{}seats_type" minOccurs="0"/>
 *         &lt;element name="wagon" type="{}wagon_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "places_type", propOrder = {
    "lower",
    "top",
    "wagon"
})
public class PlacesType {

	@XmlValue
    protected String value;
    protected SeatsType lower;
    protected SeatsType top;
    protected List<WagonType> wagon;

    public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	/**
     * Gets the value of the lower property.
     * 
     * @return
     *     possible object is
     *     {@link SeatsType }
     *     
     */
    public SeatsType getLower() {
        return lower;
    }

    /**
     * Sets the value of the lower property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeatsType }
     *     
     */
    public void setLower(SeatsType value) {
        this.lower = value;
    }

    /**
     * Gets the value of the top property.
     * 
     * @return
     *     possible object is
     *     {@link SeatsType }
     *     
     */
    public SeatsType getTop() {
        return top;
    }

    /**
     * Sets the value of the top property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeatsType }
     *     
     */
    public void setTop(SeatsType value) {
        this.top = value;
    }

    /**
     * Gets the value of the wagon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wagon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWagon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WagonType }
     * 
     * 
     */
    public List<WagonType> getWagon() {
        if (wagon == null) {
            wagon = new ArrayList<WagonType>();
        }
        return this.wagon;
    }

}
