//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.11 at 08:52:38 AM EET 
//


package com.gillsoft.client;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="merchant_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xmlsign" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_id" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="datetime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transaction">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="reserve_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="uio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="src_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="code_station_from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="code_station_to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="date1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="train" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wagon_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wagon_class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wagon_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="countrystation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="places" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fiscal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="transaction_type" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="qrcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="documents">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="document" type="{}document_type" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="binary">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="passport" type="{}passport_type"/>
 *                   &lt;element name="fiscal_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "merchantId",
    "xmlsign",
    "language",
    "productId",
    "datetime",
    "transaction"
})
@XmlRootElement(name = "request")
public class Request {

    @XmlElement(name = "merchant_id", required = true)
    protected String merchantId;
    @XmlElement(required = true)
    protected String xmlsign;
    @XmlElement(required = true)
    protected String language;
    @XmlElement(name = "product_id")
    protected int productId;
    @XmlElement(required = true)
    protected String datetime;
    @XmlElement(required = true)
    protected Request.Transaction transaction;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the merchantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * Sets the value of the merchantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantId(String value) {
        this.merchantId = value;
    }

    /**
     * Gets the value of the xmlsign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlsign() {
        return xmlsign;
    }

    /**
     * Sets the value of the xmlsign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlsign(String value) {
        this.xmlsign = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     */
    public int getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     */
    public void setProductId(int value) {
        this.productId = value;
    }

    /**
     * Gets the value of the datetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatetime() {
        return datetime;
    }

    /**
     * Sets the value of the datetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatetime(String value) {
        this.datetime = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link Request.Transaction }
     *     
     */
    public Request.Transaction getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request.Transaction }
     *     
     */
    public void setTransaction(Request.Transaction value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="reserve_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="uio" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="src_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="code_station_from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="code_station_to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="date1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="train" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="wagon_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="wagon_class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="wagon_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="countrystation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="places" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fiscal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="transaction_type" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="qrcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="documents">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="document" type="{}document_type" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="binary">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="passport" type="{}passport_type"/>
     *         &lt;element name="fiscal_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reserveId",
        "uid",
        "uio",
        "srcId",
        "name",
        "codeStationFrom",
        "codeStationTo",
        "date1",
        "train",
        "wagonType",
        "wagonClass",
        "wagonNumber",
        "date",
        "countrystation",
        "places",
        "firstname",
        "lastname",
        "fiscal",
        "transactionType",
        "qrcode",
        "barcode",
        "documents",
        "binary",
        "passport",
        "fiscalId"
    })
    public static class Transaction {

        @XmlElement(name = "reserve_id", required = true)
        protected String reserveId;
        @XmlElement(required = true)
        protected String uid;
        @XmlElement(required = true)
        protected String uio;
        @XmlElement(name = "src_id", required = true)
        protected String srcId;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(name = "code_station_from", required = true)
        protected String codeStationFrom;
        @XmlElement(name = "code_station_to", required = true)
        protected String codeStationTo;
        @XmlElement(required = true)
        protected String date1;
        @XmlElement(required = true)
        protected String train;
        @XmlElement(name = "wagon_type", required = true)
        protected String wagonType;
        @XmlElement(name = "wagon_class", required = true)
        protected String wagonClass;
        @XmlElement(name = "wagon_number", required = true)
        protected String wagonNumber;
        @XmlElement(required = true)
        protected String date;
        @XmlElement(required = true)
        protected String countrystation;
        @XmlElement(required = true)
        protected String places;
        @XmlElement(required = true)
        protected String firstname;
        @XmlElement(required = true)
        protected String lastname;
        @XmlElement(required = true)
        protected String fiscal;
        @XmlElement(name = "transaction_type")
        protected String transactionType;
        @XmlElement(required = true)
        protected String qrcode;
        @XmlElement(required = true)
        protected String barcode;
        @XmlElement(required = true)
        protected Request.Transaction.Documents documents;
        @XmlElement(required = true)
        protected Request.Transaction.Binary binary;
        @XmlElement(required = true)
        protected PassportType passport;
        @XmlElement(name = "fiscal_id", required = true)
        protected String fiscalId;
        @XmlAttribute(name = "type")
        protected String type;
        @XmlAttribute(name = "id")
        protected String id;

        /**
         * Gets the value of the reserveId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReserveId() {
            return reserveId;
        }

        /**
         * Sets the value of the reserveId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReserveId(String value) {
            this.reserveId = value;
        }

        /**
         * Gets the value of the uid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUid() {
            return uid;
        }

        /**
         * Sets the value of the uid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUid(String value) {
            this.uid = value;
        }

        /**
         * Gets the value of the uio property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUio() {
            return uio;
        }

        /**
         * Sets the value of the uio property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUio(String value) {
            this.uio = value;
        }

        /**
         * Gets the value of the srcId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrcId() {
            return srcId;
        }

        /**
         * Sets the value of the srcId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrcId(String value) {
            this.srcId = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the codeStationFrom property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodeStationFrom() {
            return codeStationFrom;
        }

        /**
         * Sets the value of the codeStationFrom property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodeStationFrom(String value) {
            this.codeStationFrom = value;
        }

        /**
         * Gets the value of the codeStationTo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodeStationTo() {
            return codeStationTo;
        }

        /**
         * Sets the value of the codeStationTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodeStationTo(String value) {
            this.codeStationTo = value;
        }

        /**
         * Gets the value of the date1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDate1() {
            return date1;
        }

        /**
         * Sets the value of the date1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate1(String value) {
            this.date1 = value;
        }

        /**
         * Gets the value of the train property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrain() {
            return train;
        }

        /**
         * Sets the value of the train property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrain(String value) {
            this.train = value;
        }

        /**
         * Gets the value of the wagonType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWagonType() {
            return wagonType;
        }

        /**
         * Sets the value of the wagonType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWagonType(String value) {
            this.wagonType = value;
        }

        /**
         * Gets the value of the wagonClass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWagonClass() {
            return wagonClass;
        }

        /**
         * Sets the value of the wagonClass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWagonClass(String value) {
            this.wagonClass = value;
        }

        /**
         * Gets the value of the wagonNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWagonNumber() {
            return wagonNumber;
        }

        /**
         * Sets the value of the wagonNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWagonNumber(String value) {
            this.wagonNumber = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(String value) {
            this.date = value;
        }

        /**
         * Gets the value of the countrystation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountrystation() {
            return countrystation;
        }

        /**
         * Sets the value of the countrystation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountrystation(String value) {
            this.countrystation = value;
        }

        /**
         * Gets the value of the places property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlaces() {
            return places;
        }

        /**
         * Sets the value of the places property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlaces(String value) {
            this.places = value;
        }

        /**
         * Gets the value of the firstname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstname() {
            return firstname;
        }

        /**
         * Sets the value of the firstname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstname(String value) {
            this.firstname = value;
        }

        /**
         * Gets the value of the lastname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastname() {
            return lastname;
        }

        /**
         * Sets the value of the lastname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastname(String value) {
            this.lastname = value;
        }

        /**
         * Gets the value of the fiscal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFiscal() {
            return fiscal;
        }

        /**
         * Sets the value of the fiscal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFiscal(String value) {
            this.fiscal = value;
        }

        /**
         * Gets the value of the transactionType property.
         * 
         */
        public String getTransactionType() {
            return transactionType;
        }

        /**
         * Sets the value of the transactionType property.
         * 
         */
        public void setTransactionType(String value) {
            this.transactionType = value;
        }

        /**
         * Gets the value of the qrcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQrcode() {
            return qrcode;
        }

        /**
         * Sets the value of the qrcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQrcode(String value) {
            this.qrcode = value;
        }

        /**
         * Gets the value of the barcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBarcode() {
            return barcode;
        }

        /**
         * Sets the value of the barcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBarcode(String value) {
            this.barcode = value;
        }

        /**
         * Gets the value of the documents property.
         * 
         * @return
         *     possible object is
         *     {@link Request.Transaction.Documents }
         *     
         */
        public Request.Transaction.Documents getDocuments() {
            return documents;
        }

        /**
         * Sets the value of the documents property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.Transaction.Documents }
         *     
         */
        public void setDocuments(Request.Transaction.Documents value) {
            this.documents = value;
        }

        /**
         * Gets the value of the binary property.
         * 
         * @return
         *     possible object is
         *     {@link Request.Transaction.Binary }
         *     
         */
        public Request.Transaction.Binary getBinary() {
            return binary;
        }

        /**
         * Sets the value of the binary property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.Transaction.Binary }
         *     
         */
        public void setBinary(Request.Transaction.Binary value) {
            this.binary = value;
        }

        /**
         * Gets the value of the passport property.
         * 
         * @return
         *     possible object is
         *     {@link PassportType }
         *     
         */
        public PassportType getPassport() {
            return passport;
        }

        /**
         * Sets the value of the passport property.
         * 
         * @param value
         *     allowed object is
         *     {@link PassportType }
         *     
         */
        public void setPassport(PassportType value) {
            this.passport = value;
        }

        /**
         * Gets the value of the fiscalId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFiscalId() {
            return fiscalId;
        }

        /**
         * Sets the value of the fiscalId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFiscalId(String value) {
            this.fiscalId = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Binary {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="document" type="{}document_type" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Documents {

            @XmlElementRef(name = "document", type = JAXBElement.class, required = false)
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * {@link JAXBElement }{@code <}{@link DocumentType }{@code >}
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

        }

    }

}
