//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.08 at 08:17:36 PM EET 
//


package com.gillsoft.client;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="merchant_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xmlsign" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_id" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="datetime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transaction">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="reserve_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="uio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="src_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="code_station_from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="code_station_to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="date1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="train" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wagon_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wagon_class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wagon_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="countrystation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="places" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fiscal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="transaction_type" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="qrcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="documents">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="document" type="{}document_type" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="binary">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="passport" type="{}passport_type"/>
 *                   &lt;element name="fiscal_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/choice>
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "merchantId",
    "xmlsign",
    "language",
    "productId",
    "datetime",
    "transaction"
})
@XmlRootElement(name = "request")
public class Request {

    @XmlElement(name = "merchant_id", required = true)
    protected String merchantId;
    @XmlElement(required = true)
    protected String xmlsign;
    @XmlElement(required = true)
    protected String language;
    @XmlElement(name = "product_id")
    protected short productId;
    @XmlElement(required = true)
    protected String datetime;
    @XmlElement(required = true)
    protected Request.Transaction transaction;
    @XmlAttribute(name = "version")
    protected Float version;

    /**
     * Gets the value of the merchantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * Sets the value of the merchantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantId(String value) {
        this.merchantId = value;
    }

    /**
     * Gets the value of the xmlsign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlsign() {
        return xmlsign;
    }

    /**
     * Sets the value of the xmlsign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlsign(String value) {
        this.xmlsign = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     */
    public short getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     */
    public void setProductId(short value) {
        this.productId = value;
    }

    /**
     * Gets the value of the datetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatetime() {
        return datetime;
    }

    /**
     * Sets the value of the datetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatetime(String value) {
        this.datetime = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link Request.Transaction }
     *     
     */
    public Request.Transaction getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request.Transaction }
     *     
     */
    public void setTransaction(Request.Transaction value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVersion(Float value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="reserve_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="uio" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="src_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="code_station_from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="code_station_to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="date1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="train" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="wagon_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="wagon_class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="wagon_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="countrystation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="places" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fiscal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="transaction_type" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="qrcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="documents">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="document" type="{}document_type" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="binary">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="passport" type="{}passport_type"/>
     *         &lt;element name="fiscal_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/choice>
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reserveIdOrUidOrUio"
    })
    public static class Transaction {

        @XmlElementRefs({
            @XmlElementRef(name = "firstname", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "transaction_type", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "date1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "wagon_class", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "lastname", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "fiscal", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "fiscal_id", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "date", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "wagon_number", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "passport", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "binary", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "places", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "uio", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "countrystation", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "code_station_to", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "qrcode", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "code_station_from", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "wagon_type", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "reserve_id", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "barcode", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "documents", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "uid", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "train", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "src_id", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<?>> reserveIdOrUidOrUio;
        @XmlAttribute(name = "type")
        protected String type;
        @XmlAttribute(name = "id")
        protected String id;

        /**
         * Gets the value of the reserveIdOrUidOrUio property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the reserveIdOrUidOrUio property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReserveIdOrUidOrUio().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link Byte }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link PassportType }{@code >}
         * {@link JAXBElement }{@code <}{@link Request.Transaction.Binary }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link Request.Transaction.Documents }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * 
         * 
         */
        public List<JAXBElement<?>> getReserveIdOrUidOrUio() {
            if (reserveIdOrUidOrUio == null) {
                reserveIdOrUidOrUio = new ArrayList<JAXBElement<?>>();
            }
            return this.reserveIdOrUidOrUio;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Binary {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="document" type="{}document_type" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Documents {

            @XmlElementRef(name = "document", type = JAXBElement.class, required = false)
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link DocumentType }{@code >}
             * {@link String }
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

        }

    }

}
