//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.11 at 08:54:19 AM EET 
//


package com.gillsoft.client;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xmlsign" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datetime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transaction">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="station" type="{}locality_type" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="uio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wait_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="date_from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="date_to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="electronic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sysdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="station_from" type="{}code_type"/>
 *                   &lt;element name="station_to" type="{}code_type"/>
 *                   &lt;element name="trains">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="train" type="{}train_type" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="train" type="{}train_type"/>
 *                   &lt;element name="wagon" type="{}wagon_type"/>
 *                   &lt;element name="date" type="{}code_type"/>
 *                   &lt;element name="countries">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="country" type="{}country_type" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="country" type="{}country_type" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="documents" type="{}ticket_type"/>
 *                   &lt;element name="order" type="{}order_type"/>
 *                   &lt;element name="document" type="{}document_type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="error" type="{}error_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xmlsign",
    "datetime",
    "transaction",
    "error"
})
@XmlRootElement(name = "response")
public class Response {

    @XmlElement(required = true)
    protected String xmlsign;
    @XmlElement(required = true)
    protected String datetime;
    @XmlElement(required = true)
    protected Response.Transaction transaction;
    @XmlElement(required = true)
    protected ErrorType error;

    /**
     * Gets the value of the xmlsign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlsign() {
        return xmlsign;
    }

    /**
     * Sets the value of the xmlsign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlsign(String value) {
        this.xmlsign = value;
    }

    /**
     * Gets the value of the datetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatetime() {
        return datetime;
    }

    /**
     * Sets the value of the datetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatetime(String value) {
        this.datetime = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link Response.Transaction }
     *     
     */
    public Response.Transaction getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.Transaction }
     *     
     */
    public void setTransaction(Response.Transaction value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setError(ErrorType value) {
        this.error = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="station" type="{}locality_type" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="uio" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="wait_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="date_from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="date_to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="electronic" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sysdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="station_from" type="{}code_type"/>
     *         &lt;element name="station_to" type="{}code_type"/>
     *         &lt;element name="trains">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="train" type="{}train_type" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="train" type="{}train_type"/>
     *         &lt;element name="wagon" type="{}wagon_type"/>
     *         &lt;element name="date" type="{}code_type"/>
     *         &lt;element name="countries">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="country" type="{}country_type" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="country" type="{}country_type" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="documents" type="{}ticket_type"/>
     *         &lt;element name="order" type="{}order_type"/>
     *         &lt;element name="document" type="{}document_type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "code",
        "text",
        "status",
        "station",
        "uio",
        "waitTime",
        "dateFrom",
        "dateTo",
        "electronic",
        "sysdate",
        "stationFrom",
        "stationTo",
        "trains",
        "train",
        "wagon",
        "date",
        "countries",
        "country",
        "documents",
        "order",
        "document"
    })
    public static class Transaction {

        @XmlElement(required = true)
        protected String code;
        @XmlElement(required = true)
        protected String text;
        @XmlElement(required = true)
        protected String status;
        protected List<LocalityType> station;
        @XmlElement(required = true)
        protected String uio;
        @XmlElement(name = "wait_time", required = true)
        protected String waitTime;
        @XmlElement(name = "date_from", required = true)
        protected String dateFrom;
        @XmlElement(name = "date_to", required = true)
        protected String dateTo;
        @XmlElement(required = true)
        protected String electronic;
        @XmlElement(required = true)
        protected String sysdate;
        @XmlElement(name = "station_from", required = true)
        protected CodeType stationFrom;
        @XmlElement(name = "station_to", required = true)
        protected CodeType stationTo;
        @XmlElement(required = true)
        protected Response.Transaction.Trains trains;
        @XmlElement(required = true)
        protected TrainType train;
        @XmlElement(required = true)
        protected WagonType wagon;
        @XmlElement(required = true)
        protected CodeType date;
        @XmlElement(required = true)
        protected Response.Transaction.Countries countries;
        protected List<CountryType> country;
        @XmlElement(required = true)
        protected TicketType documents;
        @XmlElement(required = true)
        protected OrderType order;
        protected List<DocumentType> document;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the station property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the station property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LocalityType }
         * 
         * 
         */
        public List<LocalityType> getStation() {
            if (station == null) {
                station = new ArrayList<LocalityType>();
            }
            return this.station;
        }

        /**
         * Gets the value of the uio property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUio() {
            return uio;
        }

        /**
         * Sets the value of the uio property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUio(String value) {
            this.uio = value;
        }

        /**
         * Gets the value of the waitTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWaitTime() {
            return waitTime;
        }

        /**
         * Sets the value of the waitTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWaitTime(String value) {
            this.waitTime = value;
        }

        /**
         * Gets the value of the dateFrom property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDateFrom() {
            return dateFrom;
        }

        /**
         * Sets the value of the dateFrom property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDateFrom(String value) {
            this.dateFrom = value;
        }

        /**
         * Gets the value of the dateTo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDateTo() {
            return dateTo;
        }

        /**
         * Sets the value of the dateTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDateTo(String value) {
            this.dateTo = value;
        }

        /**
         * Gets the value of the electronic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getElectronic() {
            return electronic;
        }

        /**
         * Sets the value of the electronic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setElectronic(String value) {
            this.electronic = value;
        }

        /**
         * Gets the value of the sysdate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSysdate() {
            return sysdate;
        }

        /**
         * Sets the value of the sysdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSysdate(String value) {
            this.sysdate = value;
        }

        /**
         * Gets the value of the stationFrom property.
         * 
         * @return
         *     possible object is
         *     {@link CodeType }
         *     
         */
        public CodeType getStationFrom() {
            return stationFrom;
        }

        /**
         * Sets the value of the stationFrom property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeType }
         *     
         */
        public void setStationFrom(CodeType value) {
            this.stationFrom = value;
        }

        /**
         * Gets the value of the stationTo property.
         * 
         * @return
         *     possible object is
         *     {@link CodeType }
         *     
         */
        public CodeType getStationTo() {
            return stationTo;
        }

        /**
         * Sets the value of the stationTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeType }
         *     
         */
        public void setStationTo(CodeType value) {
            this.stationTo = value;
        }

        /**
         * Gets the value of the trains property.
         * 
         * @return
         *     possible object is
         *     {@link Response.Transaction.Trains }
         *     
         */
        public Response.Transaction.Trains getTrains() {
            return trains;
        }

        /**
         * Sets the value of the trains property.
         * 
         * @param value
         *     allowed object is
         *     {@link Response.Transaction.Trains }
         *     
         */
        public void setTrains(Response.Transaction.Trains value) {
            this.trains = value;
        }

        /**
         * Gets the value of the train property.
         * 
         * @return
         *     possible object is
         *     {@link TrainType }
         *     
         */
        public TrainType getTrain() {
            return train;
        }

        /**
         * Sets the value of the train property.
         * 
         * @param value
         *     allowed object is
         *     {@link TrainType }
         *     
         */
        public void setTrain(TrainType value) {
            this.train = value;
        }

        /**
         * Gets the value of the wagon property.
         * 
         * @return
         *     possible object is
         *     {@link WagonType }
         *     
         */
        public WagonType getWagon() {
            return wagon;
        }

        /**
         * Sets the value of the wagon property.
         * 
         * @param value
         *     allowed object is
         *     {@link WagonType }
         *     
         */
        public void setWagon(WagonType value) {
            this.wagon = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link CodeType }
         *     
         */
        public CodeType getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeType }
         *     
         */
        public void setDate(CodeType value) {
            this.date = value;
        }

        /**
         * Gets the value of the countries property.
         * 
         * @return
         *     possible object is
         *     {@link Response.Transaction.Countries }
         *     
         */
        public Response.Transaction.Countries getCountries() {
            return countries;
        }

        /**
         * Sets the value of the countries property.
         * 
         * @param value
         *     allowed object is
         *     {@link Response.Transaction.Countries }
         *     
         */
        public void setCountries(Response.Transaction.Countries value) {
            this.countries = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the country property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCountry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CountryType }
         * 
         * 
         */
        public List<CountryType> getCountry() {
            if (country == null) {
                country = new ArrayList<CountryType>();
            }
            return this.country;
        }

        /**
         * Gets the value of the documents property.
         * 
         * @return
         *     possible object is
         *     {@link TicketType }
         *     
         */
        public TicketType getDocuments() {
            return documents;
        }

        /**
         * Sets the value of the documents property.
         * 
         * @param value
         *     allowed object is
         *     {@link TicketType }
         *     
         */
        public void setDocuments(TicketType value) {
            this.documents = value;
        }

        /**
         * Gets the value of the order property.
         * 
         * @return
         *     possible object is
         *     {@link OrderType }
         *     
         */
        public OrderType getOrder() {
            return order;
        }

        /**
         * Sets the value of the order property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrderType }
         *     
         */
        public void setOrder(OrderType value) {
            this.order = value;
        }

        /**
         * Gets the value of the document property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the document property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDocument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocumentType }
         * 
         * 
         */
        public List<DocumentType> getDocument() {
            if (document == null) {
                document = new ArrayList<DocumentType>();
            }
            return this.document;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="country" type="{}country_type" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Countries {

            @XmlElementRef(name = "country", type = JAXBElement.class, required = false)
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link CountryType }{@code >}
             * {@link String }
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="train" type="{}train_type" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "train"
        })
        public static class Trains {

            protected List<TrainType> train;

            /**
             * Gets the value of the train property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the train property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTrain().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TrainType }
             * 
             * 
             */
            public List<TrainType> getTrain() {
                if (train == null) {
                    train = new ArrayList<TrainType>();
                }
                return this.train;
            }

        }

    }

}
