//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.08 at 08:17:36 PM EET 
//


package com.gillsoft.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ticket_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ticket_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ordernumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fiscal_info">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rro" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="server" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="document" type="{}document_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="qr_image" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="barcode_image" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ticket_type", propOrder = {
    "ordernumber",
    "fiscalInfo",
    "document",
    "qrImage",
    "barcodeImage"
})
public class TicketType {

    @XmlElement(required = true)
    protected String ordernumber;
    @XmlElement(name = "fiscal_info", required = true)
    protected TicketType.FiscalInfo fiscalInfo;
    protected List<DocumentType> document;
    @XmlElement(name = "qr_image", required = true)
    protected String qrImage;
    @XmlElement(name = "barcode_image", required = true)
    protected String barcodeImage;

    /**
     * Gets the value of the ordernumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * Sets the value of the ordernumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdernumber(String value) {
        this.ordernumber = value;
    }

    /**
     * Gets the value of the fiscalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TicketType.FiscalInfo }
     *     
     */
    public TicketType.FiscalInfo getFiscalInfo() {
        return fiscalInfo;
    }

    /**
     * Sets the value of the fiscalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketType.FiscalInfo }
     *     
     */
    public void setFiscalInfo(TicketType.FiscalInfo value) {
        this.fiscalInfo = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the document property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentType }
     * 
     * 
     */
    public List<DocumentType> getDocument() {
        if (document == null) {
            document = new ArrayList<DocumentType>();
        }
        return this.document;
    }

    /**
     * Gets the value of the qrImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrImage() {
        return qrImage;
    }

    /**
     * Sets the value of the qrImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrImage(String value) {
        this.qrImage = value;
    }

    /**
     * Gets the value of the barcodeImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarcodeImage() {
        return barcodeImage;
    }

    /**
     * Sets the value of the barcodeImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarcodeImage(String value) {
        this.barcodeImage = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="rro" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="server" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tin" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "rro",
        "server",
        "tin"
    })
    public static class FiscalInfo {

        @XmlElement(required = true)
        protected String id;
        @XmlElement(required = true)
        protected String rro;
        @XmlElement(required = true)
        protected String server;
        @XmlElement(required = true)
        protected String tin;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the rro property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRro() {
            return rro;
        }

        /**
         * Sets the value of the rro property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRro(String value) {
            this.rro = value;
        }

        /**
         * Gets the value of the server property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServer() {
            return server;
        }

        /**
         * Sets the value of the server property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServer(String value) {
            this.server = value;
        }

        /**
         * Gets the value of the tin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTin() {
            return tin;
        }

        /**
         * Sets the value of the tin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTin(String value) {
            this.tin = value;
        }

    }

}
